### ISSUE TITLE
[SOLVED] Fpga Programming - DNA

### ISSUE THREAD

**Issue by nebiljabari** [matrix-io/matrix-creator-quickstart#11]
I get a different DNA code You: `DNA is 0x39c620e4bfe15bfd` Me: `DNA is 0x19de808ee0299afd`

Is it normal ? If yes (which I assume) could you please put a note in the page to indicate so

**Comment by kdpatino** [comment]
Hello @nebiljabari DNA code its a unique number of your FPGA, so each FPGA has different DNA number. 

BR,
Kevin
