### ISSUE TITLE
npm package of zmq on MAC 

### ISSUE THREAD

**Issue by Yoriichi0shiki** [matrix-io/matrix-creator-quickstart#14]
when  execute the test for javascript of malos in a MAC pc, and runs `npm install` the package of zmq shows this error: 

`gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp`

**Comment by Yoriichi0shiki** [comment]
run `brew install zeromq` before `npm install`.

**Note:** This is for Mac-only install of `matrix-os`.

**Comment by brianofrokk3r** [comment]
@alvajardila if you follow the documentation [here](https://matrix-io.github.io/matrix-documentation/), you will be led to install `libzmq3-dev` as a dependency before `npm install`.

**Note:** This is for Raspberry Pi.
